version: "3"

networks:
  d.net:
    driver: bridge

services:

# Service d'events/messages
  events.service:
    image: canals/php:latest
    environment:
      - VHOST_HOSTNAME=events.service.local
      - VHOST_DOCROOT=/var/www/web
    ports:
      - "62010:80"
    volumes:
      - ./events_service/public:/var/www/web
      - ./events_service/src:/var/www/src
    working_dir: /var/www/web
    networks:
      - d.net
    links:
      - mysql.events:db

# Service d'utilisateurs
  auth.service:
    image: canals/php:latest
    ports:
      - "62011:80"
    volumes:
      - ./auth_service/public:/var/www/html
      - ./auth_service/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - d.net
    links:
      - mysql.users:db

# ###############
# #  service apache pour la webapp front
# #  service accessible sur http://docketu.iutnc.univ-lorraine.fr:19280
# ###############

#   webfront:
#     image: httpd:latest
#     # environment:
#     #   - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
#     #   - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
#     ports:
#       - "62012:80"
#     volumes:
#       - ./front/public:/usr/local/apache2/htdocs
#     working_dir: /usr/local/apache2/htdocs
#     networks:
#       - d.net


#############################
# mysql + phpmyadmin
#############################
# Base de données d'events/messages
  mysql.events:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root456
      - MYSQL_USER=events
      - MYSQL_PASSWORD=events
      - MYSQL_DATABASE=mysql.events
    volumes :
      - ./events_service/sql:/var/sql
    ports:
      - 6307:3306
    networks:
      - d.net

# Base de données d'utilisateurs
  mysql.users:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_USER=users
      - MYSQL_PASSWORD=users
      - MYSQL_DATABASE=mysql.users
    volumes :
      - ./auth_service/sql:/var/sql
    ports:
      - 3307:3306
    networks:
      - d.net

# Administration des bases de données
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - d.net
